language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libz-dev
      - libbz2-dev
      - gengetopt
before_script:
  - autoreconf -i
script:
  # non-default options because distcheck checks default ones later on
  - ./configure --without-zlib --without-bzlib --enable-single --disable-openmp && make && ./debyer/debyer --bench=5000 && make distcheck
branches:
  only:
    - master
notifications:
  email:
    - wojdyr@gmail.com
