language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -qq libz-dev libbz2-dev gengetopt
before_script:
  - autoreconf -i
script:
  # non-default options because distcheck checks default ones later on
  - ./configure --without-zlib --without-bzlib --enable-single --disable-openmp && make && ./debyer/debyer --bench=5000 && make distcheck
branches:
  only:
    - master
notifications:
  recipients:
    - wojdyr@gmail.com
  email:
    on_success: change
    on_failure: always
